USE [master]
GO
/****** Object:  Database [webQLQuanAn]    Script Date: 9/16/2025 4:08:26 PM ******/
CREATE DATABASE [webQLQuanAn]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'webQLQuanAn_Data', FILENAME = N'/var/opt/mssql/data\webQLQuanAn.mdf' , SIZE = 10240KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'webQLQuanAn_Log', FILENAME = N'/var/opt/mssql/data\webQLQuanAn.ldf' , SIZE = 23616KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [webQLQuanAn] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [webQLQuanAn].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [webQLQuanAn] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [webQLQuanAn] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [webQLQuanAn] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [webQLQuanAn] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [webQLQuanAn] SET ARITHABORT OFF 
GO
ALTER DATABASE [webQLQuanAn] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [webQLQuanAn] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [webQLQuanAn] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [webQLQuanAn] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [webQLQuanAn] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [webQLQuanAn] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [webQLQuanAn] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [webQLQuanAn] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [webQLQuanAn] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [webQLQuanAn] SET  DISABLE_BROKER 
GO
ALTER DATABASE [webQLQuanAn] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [webQLQuanAn] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [webQLQuanAn] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [webQLQuanAn] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [webQLQuanAn] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [webQLQuanAn] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [webQLQuanAn] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [webQLQuanAn] SET RECOVERY FULL 
GO
ALTER DATABASE [webQLQuanAn] SET  MULTI_USER 
GO
ALTER DATABASE [webQLQuanAn] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [webQLQuanAn] SET DB_CHAINING OFF 
GO
ALTER DATABASE [webQLQuanAn] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [webQLQuanAn] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [webQLQuanAn] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [webQLQuanAn] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'webQLQuanAn', N'ON'
GO
ALTER DATABASE [webQLQuanAn] SET QUERY_STORE = ON
GO
ALTER DATABASE [webQLQuanAn] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [webQLQuanAn]
GO
/****** Object:  Table [dbo].[[Bill]]]    Script Date: 9/16/2025 4:08:29 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[[Bill]]](
	[BillID] [char](10) NOT NULL,
	[Total] [decimal](18, 2) NULL,
	[Discount] [decimal](18, 2) NULL,
	[TotalFinal] [decimal](18, 2) NULL,
	[Payment] [nvarchar](50) NULL,
	[CreatedTime] [datetime] NULL,
	[OrderID] [char](10) NULL,
	[UserID] [char](10) NULL,
 CONSTRAINT [PK_Bill] PRIMARY KEY CLUSTERED 
(
	[BillID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[[Bill_Detail]]]    Script Date: 9/16/2025 4:08:30 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[[Bill_Detail]]](
	[BillID] [char](10) NOT NULL,
	[OrderID] [char](10) NOT NULL,
	[Quantity] [int] NULL,
	[UnitPrice] [decimal](18, 2) NULL,
 CONSTRAINT [PK_Bill_Detail] PRIMARY KEY CLUSTERED 
(
	[OrderID] ASC,
	[BillID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[[Category]]]    Script Date: 9/16/2025 4:08:30 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[[Category]]](
	[CateID] [char](10) NOT NULL,
	[CateName] [nvarchar](50) NULL,
	[Description] [nvarchar](200) NULL,
 CONSTRAINT [PK_Category] PRIMARY KEY CLUSTERED 
(
	[CateID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [IX_Category] UNIQUE NONCLUSTERED 
(
	[CateName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[[Food_Info]]]    Script Date: 9/16/2025 4:08:30 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[[Food_Info]]](
	[FoodID] [char](10) NOT NULL,
	[FoodName] [nvarchar](100) NOT NULL,
	[FoodImage] [varchar](max) NULL,
	[UnitPrice] [decimal](18, 2) NULL,
	[Description] [nvarchar](300) NULL,
	[CateID] [char](10) NULL,
 CONSTRAINT [PK_Food_Info] PRIMARY KEY CLUSTERED 
(
	[FoodID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [IX_Food_Info] UNIQUE NONCLUSTERED 
(
	[FoodName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[[Ingredient]]]    Script Date: 9/16/2025 4:08:30 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[[Ingredient]]](
	[IngreID] [char](10) NOT NULL,
	[IngreName] [nvarchar](100) NOT NULL,
	[Stock] [bigint] NULL,
	[UnitMeasurement] [nvarchar](50) NULL,
 CONSTRAINT [PK_Ingredient] PRIMARY KEY CLUSTERED 
(
	[IngreID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [IX_Ingredient] UNIQUE NONCLUSTERED 
(
	[IngreName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[[Order]]]    Script Date: 9/16/2025 4:08:30 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[[Order]]](
	[OrderID] [char](10) NOT NULL,
	[CreatedTime] [datetime] NULL,
	[Status] [nvarchar](20) NULL,
	[Total] [decimal](18, 2) NULL,
	[Note] [nvarchar](200) NULL,
	[Discount] [decimal](18, 2) NULL,
	[TableID] [char](10) NULL,
	[ReservationID] [char](10) NULL,
	[UserID] [char](10) NULL,
 CONSTRAINT [PK_Order] PRIMARY KEY CLUSTERED 
(
	[OrderID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[[Order_Detail]]]    Script Date: 9/16/2025 4:08:30 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[[Order_Detail]]](
	[FoodID] [char](10) NOT NULL,
	[OrderID] [char](10) NOT NULL,
	[UnitPrice] [decimal](18, 2) NULL,
	[Status] [nvarchar](20) NULL,
	[Quantity] [int] NULL,
 CONSTRAINT [PK_Order_Detail_1] PRIMARY KEY CLUSTERED 
(
	[FoodID] ASC,
	[OrderID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[[Recipe]]]    Script Date: 9/16/2025 4:08:30 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[[Recipe]]](
	[RecipeID] [char](10) NOT NULL,
	[RecipeDescription] [nvarchar](200) NULL,
	[FoodID] [char](10) NULL,
 CONSTRAINT [PK_Recipe] PRIMARY KEY CLUSTERED 
(
	[RecipeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[[Recipe_Detail]]]    Script Date: 9/16/2025 4:08:30 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[[Recipe_Detail]]](
	[RecipeID] [char](10) NOT NULL,
	[IngreID] [char](10) NOT NULL,
	[UnitMeasurement] [nvarchar](20) NULL,
	[Quantity] [bigint] NULL,
 CONSTRAINT [PK_Recipe_Detail] PRIMARY KEY CLUSTERED 
(
	[RecipeID] ASC,
	[IngreID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[[Table]]]    Script Date: 9/16/2025 4:08:30 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[[Table]]](
	[TableID] [char](10) NOT NULL,
	[TableName] [nvarchar](20) NULL,
	[NumOfSeats] [int] NULL,
	[Status] [nvarchar](20) NULL,
 CONSTRAINT [PK_Table] PRIMARY KEY CLUSTERED 
(
	[TableID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [IX_Table] UNIQUE NONCLUSTERED 
(
	[TableName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[[User]]]    Script Date: 9/16/2025 4:08:30 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[[User]]](
	[UserID] [char](10) NOT NULL,
	[UserName] [varchar](50) NOT NULL,
	[Password] [varchar](20) NOT NULL,
	[Role] [nvarchar](25) NULL,
	[Right] [nvarchar](25) NULL,
	[FullName] [nvarchar](250) NULL,
	[Phone] [int] NULL,
	[Email] [nvarchar](100) NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [IX_User] UNIQUE NONCLUSTERED 
(
	[UserName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [IX_User_1] UNIQUE NONCLUSTERED 
(
	[Phone] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [IX_User_2] UNIQUE NONCLUSTERED 
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[[Bill]]]  WITH CHECK ADD  CONSTRAINT [FK_Bill_Order] FOREIGN KEY([OrderID])
REFERENCES [dbo].[[Order]]] ([OrderID])
GO
ALTER TABLE [dbo].[[Bill]]] CHECK CONSTRAINT [FK_Bill_Order]
GO
ALTER TABLE [dbo].[[Bill]]]  WITH CHECK ADD  CONSTRAINT [FK_Bill_User] FOREIGN KEY([UserID])
REFERENCES [dbo].[[User]]] ([UserID])
GO
ALTER TABLE [dbo].[[Bill]]] CHECK CONSTRAINT [FK_Bill_User]
GO
ALTER TABLE [dbo].[[Bill_Detail]]]  WITH CHECK ADD  CONSTRAINT [FK_Bill_Detail_Bill] FOREIGN KEY([BillID])
REFERENCES [dbo].[[Bill]]] ([BillID])
GO
ALTER TABLE [dbo].[[Bill_Detail]]] CHECK CONSTRAINT [FK_Bill_Detail_Bill]
GO
ALTER TABLE [dbo].[[Bill_Detail]]]  WITH CHECK ADD  CONSTRAINT [FK_Bill_Detail_Order] FOREIGN KEY([OrderID])
REFERENCES [dbo].[[Order]]] ([OrderID])
GO
ALTER TABLE [dbo].[[Bill_Detail]]] CHECK CONSTRAINT [FK_Bill_Detail_Order]
GO
ALTER TABLE [dbo].[[Food_Info]]]  WITH CHECK ADD  CONSTRAINT [FK_Food_Info_Category] FOREIGN KEY([CateID])
REFERENCES [dbo].[[Category]]] ([CateID])
GO
ALTER TABLE [dbo].[[Food_Info]]] CHECK CONSTRAINT [FK_Food_Info_Category]
GO
ALTER TABLE [dbo].[[Order]]]  WITH CHECK ADD  CONSTRAINT [FK_Order_Table] FOREIGN KEY([TableID])
REFERENCES [dbo].[[Table]]] ([TableID])
GO
ALTER TABLE [dbo].[[Order]]] CHECK CONSTRAINT [FK_Order_Table]
GO
ALTER TABLE [dbo].[[Order]]]  WITH CHECK ADD  CONSTRAINT [FK_Order_User] FOREIGN KEY([UserID])
REFERENCES [dbo].[[User]]] ([UserID])
GO
ALTER TABLE [dbo].[[Order]]] CHECK CONSTRAINT [FK_Order_User]
GO
ALTER TABLE [dbo].[[Order_Detail]]]  WITH CHECK ADD  CONSTRAINT [FK_Order_Detail_Food_Info] FOREIGN KEY([FoodID])
REFERENCES [dbo].[[Food_Info]]] ([FoodID])
GO
ALTER TABLE [dbo].[[Order_Detail]]] CHECK CONSTRAINT [FK_Order_Detail_Food_Info]
GO
ALTER TABLE [dbo].[[Order_Detail]]]  WITH CHECK ADD  CONSTRAINT [FK_Order_Detail_Order] FOREIGN KEY([OrderID])
REFERENCES [dbo].[[Order]]] ([OrderID])
GO
ALTER TABLE [dbo].[[Order_Detail]]] CHECK CONSTRAINT [FK_Order_Detail_Order]
GO
ALTER TABLE [dbo].[[Recipe]]]  WITH CHECK ADD  CONSTRAINT [FK_Recipe_Food_Info] FOREIGN KEY([FoodID])
REFERENCES [dbo].[[Food_Info]]] ([FoodID])
GO
ALTER TABLE [dbo].[[Recipe]]] CHECK CONSTRAINT [FK_Recipe_Food_Info]
GO
ALTER TABLE [dbo].[[Recipe_Detail]]]  WITH CHECK ADD  CONSTRAINT [FK_Recipe_Detail_Ingredient] FOREIGN KEY([IngreID])
REFERENCES [dbo].[[Ingredient]]] ([IngreID])
GO
ALTER TABLE [dbo].[[Recipe_Detail]]] CHECK CONSTRAINT [FK_Recipe_Detail_Ingredient]
GO
ALTER TABLE [dbo].[[Recipe_Detail]]]  WITH CHECK ADD  CONSTRAINT [FK_Recipe_Detail_Recipe_Detail] FOREIGN KEY([RecipeID])
REFERENCES [dbo].[[Recipe]]] ([RecipeID])
GO
ALTER TABLE [dbo].[[Recipe_Detail]]] CHECK CONSTRAINT [FK_Recipe_Detail_Recipe_Detail]
GO
/****** Object:  StoredProcedure [dbo].[sp_UpdateOrderStatus]    Script Date: 9/16/2025 4:08:30 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[sp_UpdateOrderStatus]
    @OrderID CHAR(10)
AS
BEGIN
    SET NOCOUNT ON;

    -- Kiểm tra nếu không tồn tại chi tiết món
    IF NOT EXISTS (SELECT 1 FROM [[Order_Detail]]] WHERE OrderID = @OrderID)
        RETURN;

    -- Nếu tất cả món đều Hoàn tất
    IF NOT EXISTS (
        SELECT 1 FROM [[Order_Detail]]]
        WHERE OrderID = @OrderID AND Status <> N'Hoàn tất'
    )
    BEGIN
        UPDATE [[Order]]]
        SET Status = N'Hoàn tất'
        WHERE OrderID = @OrderID;
    END
    -- Nếu có ít nhất một món là Đang xử lý hoặc Hoàn tất
    ELSE IF EXISTS (
        SELECT 1 FROM [[Order_Detail]]]
        WHERE OrderID = @OrderID AND (Status = N'Đang xử lý' OR Status = N'Hoàn tất')
    )
    BEGIN
        UPDATE [[Order]]]
        SET Status = N'Đang xử lý'
        WHERE OrderID = @OrderID;
    END
    ELSE
    BEGIN
        UPDATE [[Order]]]
        SET Status = N'Chưa làm'
        WHERE OrderID = @OrderID;
    END
END;
GO
USE [master]
GO
ALTER DATABASE [webQLQuanAn] SET  READ_WRITE 
GO
